filipedeschamps/rss-feed-emitter

test/rss-fee-emitter.spec.js

E verifica se os objetos possuem todas as propriedades necessárias.

test(list): adiciona primeiros testes para o método #list

---

test/rss-fee-emitter.spec.js

E retorna por default um array em branco. Também ajusta alguns espaçamentos nos outros testes.

test(list): garante a interface do #list ser uma função

---

package.json

Vamos começar a fazer o parse dos feeds com estes dois.

feat(module): adiciona `request` e `feedparser` como dependência

---

package.json

Não estou feliz com isto neste momento, pois só estou utilizando no
.bind(this) de uma promise.

feat(module): adiciona o Bluebird

---

src/rss-feed-emitter.js

Agora o módulo faz o fetch dos dados do feed, reorganiza, identifica
quais são os itens novos (isto precisa melhorar), adiciona os itens
novos no feed e emite o evento `new-item`.
Closes #22
Closes #28
Closes #29
Closes #30
Closes #31
Closes #32

feat(add): adiciona implementação de fetch dos feeds

---

test/rss-fee-emitter.spec.js

E mais para frente vou precisar fazer o mock dos dados e separar em uma
pasta de teste unitário.
Closes #34

test(on): adiciona case para `on('new-item')`

---

test/unit/fixtures/nintendo-latest-first-fetch.xml
test/unit/fixtures/nintendo-latest-second-fetch.xml
test/unit/fixtures/nintendo-news-first-fetch.xml
test/unit/fixtures/nintendo-news-second-fetch.xml
test/unit/rss-feed-emitter.spec.js

Agora de fato os testes ficaram unitários, pois não é feito mais a
request para a network.
Closes #37

test(unit): faz mock de todas as requests

---

test/unit/rss-feed-emitter.spec.js

Estamos utilizando novamente o Nock para fazer o teste de um segundo
fetch do feed com 9 notícias novas.
Closes #42

test(on): verifica se somente novos itens são emitidos

---

src/rss-feed-emitter.js

Agora independente de como as datas do feed vierem, será emitido na
ordem crescente da data.
Closes #46

feat(emit): forçar emissão de itens na ordem correta

---

test/unit/rss-feed-emitter.spec.js

Para aproximar o escopo do mock e dos testes, coloquei a declaração do
nock de forma inline em todos os specs. Assim saberemos de forma mais
clara qual mock está definido para cada situação.
Closes #49

test(nock): refatora o Nock dentro dos testes

---

test/unit/rss-feed-emitter.spec.js

Sempre emitindo em ordem crescente da data do item.
Closes #51

test(new-item): garante que os itens sejam emitidos na ordem certa

---

package.json

Atualizando a interface do Babel

chore(babel): bump Babel version

---

src/rss-feed-emitter.js

Isto serve para ele não ocupar muita memória.
Closes #54

feat(history): adiciona limite para o histórico do feed

---

src/rss-feed-emitter.js
test/unit/fixtures/nintendo-latest-fourth-fetch.xml
test/unit/rss-feed-emitter.spec.js

Inclusive, remove todas as funções da cadeia do fetch do escopo global e
coloca elas dentro do escopo privado desta rotina.
Closes #56

refactor(fetch): altera toda lógica do fetch

---

src/rss-feed-emitter.js
test/unit/rss-feed-emitter.spec.js

Agora eles emitem um objeto que possui "type" para melhor identificar
programaticamente e não ficar preso apenas a string "message".
Closes #60

feat(errors): padroniza todos os erros

---

test/unit/rss-feed-emitter.spec.js

text(new-item): garante certas propriedades do item emitido

---

src/rss-feed-emitter.js

fix(find-item): search using item.link and item.title

---

package.json

chore(package): remove `test-watch` script

---

test/unit/rss-feed-emitter.spec.js

And normalizes error/throw names.
Closes #73

test(translate): finish translation to english

---

.babelrc
dist/rss-feed-emitter.js
package.json

Now you can correctly require this module with an ES5 environment.
Closes #79

chore(dist): create distribution scripts

---

README.md

The badge image is offline all the time

chore(readme): remove dependencies badge

---

src/rss-feed-emitter.js

Find items in feeds by unique id

---

src/rss-feed-emitter.js

More info [here](https://www.youtube.com/watch?v=rLnDdKyeWZo)

Object Short Notation

---

.travis.yml
README.md
package.json

chore(package): bump request module

---

src/rss-feed-emitter.js
test/integration/rss-feed-emitter.spec.js

@tolgacesur please take a look, I've added e2e tests to your implementation.
I'm closing your PR https://github.com/filipedeschamps/rss-feed-emitter/pull/167

Add text/xml to request accept header (with e2e tests)

---

src/Feed.js
src/FeedError.js
test/unit/rss-feed-emitter.spec.js

Hi,
great library!
It seems its more strict in v3, as some of my feeds now fail due 404 and more. But i fixed them :)
Cheers
midzer

improve FeedError message

---

src/FeedManager.js

closes #190
solution provided by @mfreiwald

fix: first load filter not working

---

README.md

chore(docs): fix some inaccurate docs

---

package-lock.json
package.json
src/Feed.js
src/FeedEmitter.js
src/FeedError.js
src/FeedItem.js
src/FeedManager.js
tsconfig.declaration.json

- Use the correct module resolution for generating types
- Remove typedefs from class declarations
- Add missing public/private declarations
- fix config to be reflect code level

Fix type generation
